export default {
  showStudentForm: false,
  showStudentList: true,
  studentToEdit: 0,
  showAcademicYearForm: false,
  showAcademicYearList: true,
  academicYearToEdit: 0,
  showCourseForm: false,
  showCourseList: true,
  courseToEdit: 0,
  showTeacherForm: false,
  showTeacherList: true,
  teacherToEdit: 0,
  showHomeworkForm: false,
  showHomeworkList: true,
  homeworkToEdit: 0,
};
